name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: yeezy
          template: classic
          base: activity, metadata
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
